function plot_ascat(mean_U,mean_V,count,extras)
%This function plots ascat wind vector grids and data count matrix using mmap.

%INPUTS: mean_U, mean_V and count are generated by ascat_avg2.



x=extras.start_lon+extras.d_lon/2:extras.d_lon:extras.end_lon+extras.d_lon/2;
y=extras.start_lat+extras.d_lat/2:extras.d_lat:extras.end_lat+extras.d_lat/2;
x1=(extras.start_lon):extras.d_lon:(extras.end_lon+extras.d_lon);
y1=(extras.start_lat):extras.d_lat:(extras.end_lat+extras.d_lat);
m_proj('Lambert','lat',[extras.start_lat,extras.end_lat],'lon',[extras.start_lon,extras.end_lon])
[X,Y] = meshgrid(x,y);
[X1,Y1] = meshgrid(x1,y1);
figure
m_quiver(X,Y,mean_U,mean_V);
m_gshhs_i('color','k')
m_grid

% figure
% count(end+1,:) = 0;
% count(:,end+1) = 0;
% m_pcolor(X1,Y1,count(:,:)');
% m_gshhs_i('color','k')
% m_grid
end